== ABOUT

image:++./back-to-my-homepage-logo/back-to-my-homepage--scripted-final--with-gradient-applied--cropped.svg++[Back to my Homepage logo]

This is the new and https://inkscape.org/[Inkscape]-based version of
Shlomi Fish’s web graphics image reading “Back to my Homepage” in the
style of the logo of the film
http://en.wikipedia.org/wiki/Back_to_the_Future[Back to the Future] .

Its homepage is now at
http://www.shlomifish.org/art/back-to-my-homepage-2nd-ver/ .

The previous version, which was done using CorelDRAW, can be found on
http://www.shlomifish.org/art/bk2hp/[its page on Shlomi Fish’s site],
but its source CDR, and the available, GIF file result may not be too usable.

== HOW TO USE

See the README file in the link:back-to-my-homepage-logo/[sub-directory]
for more information.

== LICENSE

The original logo of the _Back to the Future_ film, may be protected by
copyrights and trademarks, and since this logo emulates it, it may be
considered derivative work. The content itself is original, but uses
some GPLed and other open source code. As far as I'm (= Shlomi Fish) is
concerned the intermediate and final .svg files can be used under the
CC-Zero / Public Domain (see
https://creativecommons.org/publicdomain/zero/1.0/ ). Crediting me as
the originator of the works will be appreciated, but not absolutely
necessary.
