=encoding utf8

=head1 ABOUT

This is the new and Inkscape-based version of Shlomi Fish’s web graphics
reading “Back to my Homepage” in the style of the logo of the film
L<Back to the Future|http://en.wikipedia.org/wiki/Back_to_the_Future> .
The previous version, which was done using CorelDRAW, can be found at
L<its page on Shlomi Fish’s site|http://www.shlomifish.org/art/bk2hp/>,
but its CDR and resulting GIF may not be too usable.

=head1 HOW TO USE

See the README file in the below directory for more information.

=head1 LICENSE

The original logo of the I<Back to the Future> film, may be protected by
copyrights and trademarks, and since this logo emulates it, it may be
considered derivative work. The content itself is original, but uses some
GPLed and other open source code. As far as I'm (= Shlomi Fish) is
concerned the intermediate and final .svg files can be used under the CC-Zero
/ Public Domain (see L<https://creativecommons.org/publicdomain/zero/1.0/> ).
Crediting me as the originator of the works will be appreciated, but not
absolutely necessary.

=cut

