all:

INKSCAPE_EXTENSIONS_INSTALL_DIR = "$${HOME}/.config/inkscape/extensions/"

install:
	mkdir -p $(INKSCAPE_EXTENSIONS_INSTALL_DIR)
	cp -f add_path.inx add_path.py shlomif_back_to_homepage_distort.inx shlomif_back_to_homepage_distort.py $(INKSCAPE_EXTENSIONS_INSTALL_DIR)
